---
title: "Clarence Stein Institute of Urban and Landscape Studies: Interactive Database Viewer"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: united
    horizontal_layout: fill
    social: menu
---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)
library(crosstalk)
library(mapview)
library(tidyverse)
library(lubridate)

```

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}

```

---

**Database:**  
This database provides an interactive interface to view the projects that have been funded by the Clarence Stein Institute from 2004-2016. The databse has been classified based on the three award categories and the details of the project can be found in the adjoining table. The map points to the the areas studied across these 147 projects, spanning five continents and over 20 countries. Click on the relevant points for details of previously funded projects. 

Row {data-height=400}
-----------------------------------------------------------------------

```{r}
library(leaflet)
leaflet(Maharashtra_sp)%>%addProviderTiles(providers$OpenStreetMap)%>%addPolygons()

```

Row {data-height=600}
-----------------------------------------------------------------------

```{r}
library(DT)
```
